"""create_pollution_data_table

Revision ID: c3076446e47c
Revises: 
Create Date: 2024-11-16 20:06:28.677578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3076446e47c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pollution_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('air_quality_index', sa.Integer(), nullable=False),
    sa.Column('water_quality_index', sa.Integer(), nullable=False),
    sa.Column('ph_level', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pollution_data')
    # ### end Alembic commands ###
